"""
Multi-Language Code Generator

Generates crawler code in multiple programming languages:
- Python (httpx, requests)
- Node.js (axios, node-fetch)
- Go (net/http)
- Shell (curl)

Version: 1.0
Created: 2026-04-06
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional


@dataclass
class CodeGenConfig:
    """Configuration for code generation"""
    language: str = "python"  # python, nodejs, go, curl
    library: str = "httpx"  # httpx, requests, axios, fetch, nethttp
    include_retry: bool = True
    include_rate_limit: bool = True
    include_proxy: bool = False
    include_captcha: bool = False
    timeout: int = 30
    max_retries: int = 3


class MultiLangCodeGenerator:
    """
    Generate crawler code in multiple programming languages.
    """
    
    def generate(
        self,
        url: str,
        method: str = "GET",
        headers: Optional[dict] = None,
        params: Optional[dict] = None,
        body: Optional[dict] = None,
        signature_logic: Optional[dict] = None,
        config: Optional[CodeGenConfig] = None,
    ) -> str:
        """
        Generate code based on configuration.
        
        Args:
            url: Target URL
            method: HTTP method
            headers: Request headers
            params: URL parameters
            body: Request body
            signature_logic: Signature generation logic
            config: Generation configuration
            
        Returns:
            Generated code as string
        """
        config = config or CodeGenConfig()
        
        generators = {
            "python": self._generate_python,
            "nodejs": self._generate_nodejs,
            "go": self._generate_go,
            "curl": self._generate_curl,
        }
        
        generator = generators.get(config.language, self._generate_python)
        return generator(url, method, headers, params, body, signature_logic, config)
    
    def _generate_python(
        self,
        url: str,
        method: str,
        headers: Optional[dict],
        params: Optional[dict],
        body: Optional[dict],
        signature_logic: Optional[dict],
        config: CodeGenConfig,
    ) -> str:
        """Generate Python code"""
        
        if config.library == "httpx":
            imports = "import httpx\nimport hashlib\nimport hmac\nimport base64\nimport time\nimport random\nimport json"
            client = "httpx.Client"
            request = "client.request"
        else:
            imports = "import requests\nimport hashlib\nimport hmac\nimport base64\nimport time\nimport random\nimport json"
            client = "requests.Session"
            request = "session.request"
        
        code = f'''"""
Python Crawler - Generated by Axelo JSReverse
Target: {url}
"""
from __future__ import annotations

{imports}


class Crawler:
    def __init__(self):
        self.session = {client}(timeout={config.timeout})'''
        
        if config.include_retry:
            code += f'''
        self.max_retries = {config.max_retries}
        self.retry_delay = 1'''
        
        code += '''
    
    def generate_signature(self, params: dict) -> str:
        """Generate request signature based on analysis"""
'''
        
        if signature_logic:
            algo = signature_logic.get("algorithm", "hmac-sha256")
            if "hmac" in algo.lower():
                code += f'''
        secret = "{signature_logic.get("key", "secret")}"
        message = self._build_message(params)
        signature = hmac.new(
            secret.encode(),
            message.encode(),
            hashlib.sha256
        ).hexdigest()
        return signature'''
            elif "sha" in algo.lower():
                code += f'''
        message = self._build_message(params)
        signature = hashlib.sha256(message.encode()).hexdigest()
        return signature'''
            else:
                code += '''
        # Custom signature logic needed
        return ""'''
        else:
            code += '''
        # Signature logic not detected
        return ""'''
        
        code += '''
    
    def _build_message(self, params: dict) -> str:
        """Build message string from parameters"""
        # Sort keys and concatenate
        sorted_params = sorted(params.items())
        return "&".join(f"{k}={v}" for k, v in sorted_params)
    
    def make_request(
        self,
        url: str,
        method: str = "GET",
        params: Optional[dict] = None,
        headers: Optional[dict] = None,
        data: Optional[dict] = None,
    ):
        """Make HTTP request with retry logic"""
'''
        
        if config.include_retry:
            code += '''
        for attempt in range(self.max_retries):
            try:
'''
        
        code += f'''
                response = self.{request}(
                    method=method,
                    url=url,
                    params=params,
                    headers=headers,
                    json=data,
                )
                response.raise_for_status()
                return response'''
        
        if config.include_retry:
            code += '''
            except Exception as e:
                if attempt < self.max_retries - 1:
                    time.sleep(self.retry_delay * (attempt + 1))
                    continue
                raise
        
        return None'''
        
        code += '''


def main():
    crawler = Crawler()
    
    # Example usage
    url = "{url}"
    
    params = {params}
    headers = {headers}
    
    response = crawler.make_request(url, method="{method}", params=params, headers=headers)
    
    if response:
        print(f"Status: {{response.status_code}}")
        print(f"Response: {{response.text[:500]}}")


if __name__ == "__main__":
    main()
'''.format(
            url=url,
            params=params or {},
            headers=headers or {"User-Agent": "Mozilla/5.0"},
            method=method,
        )
        
        return code
    
    def _generate_nodejs(
        self,
        url: str,
        method: str,
        headers: Optional[dict],
        params: Optional[dict],
        body: Optional[dict],
        signature_logic: Optional[dict],
        config: CodeGenConfig,
    ) -> str:
        """Generate Node.js code"""
        
        if config.library == "axios":
            import_stmt = "const axios = require('axios');"
            request = "axios"
        else:
            import_stmt = "const fetch = require('node-fetch');"
            request = "fetch"
        
        code = f'''/**
 * Node.js Crawler - Generated by Axelo JSReverse
 * Target: {url}
 */

{import_stmt}
const crypto = require('crypto');

class Crawler {{
    constructor() {{
        this.baseURL = "{url.split('?')[0]}";
        this.defaultHeaders = {json.dumps(headers or {{}}, indent=8)};
    }}
'''
        
        if config.include_retry:
            code += f'''
    async requestWithRetry(url, options, maxRetries = {config.max_retries}) {{
        for (let attempt = 0; attempt < maxRetries; attempt++) {{
            try {{
                const response = await {request}(url, options);
                return response;
            }} catch (error) {{
                if (attempt < maxRetries - 1) {{
                    await new Promise(r => setTimeout(r, 1000 * (attempt + 1)));
                    continue;
                }}
                throw error;
            }}
        }}
    }}
'''
        
        code += f'''
    generateSignature(params) {{
        // Signature generation logic
        const message = Object.keys(params).sort()
            .map(k => `${{k}}=${{params[k]}}`)
            .join('&');
'''
        
        if signature_logic:
            code += f'''
        const secret = "{signature_logic.get("key", "secret")}";
        const hmac = crypto.createHmac('sha256', secret);
        return hmac.update(message).digest('hex');'''
        else:
            code += '''
        // Signature logic not detected
        return "";'''
        
        code += '''
    }
'''
        
        code += f'''
    async makeRequest(path = "", method = "{method}", data = null) {{
        const params = {params or {{}}};
'''
        
        if config.include_retry:
            code += '''
        const response = await this.requestWithRetry(
            this.baseURL + path,
            {{
                method,
                headers: this.defaultHeaders,
                body: data ? JSON.stringify(data) : null,
            }}
        );
'''
        else:
            code += '''
        const response = await fetch(
            this.baseURL + path,
            {
                method,
                headers: this.defaultHeaders,
                body: data ? JSON.stringify(data) : null,
            }
        );
'''
        
        code += '''
        return response.json();
    }
}

const crawler = new Crawler();
crawler.makeRequest().then(console.log).catch(console.error);
'''
        
        return code
    
    def _generate_go(
        self,
        url: str,
        method: str,
        headers: Optional[dict],
        params: Optional[dict],
        body: Optional[dict],
        signature_logic: Optional[dict],
        config: CodeGenConfig,
    ) -> str:
        """Generate Go code"""
        
        code = f'''package main

import (
    "crypto/hmac"
    "crypto/sha256"
    "encoding/base64"
    "fmt"
    "io/ioutil"
    "net/http"
    "net/url"
    "strings"
    "time"
)

type Crawler struct {{
    client  *http.Client
    baseURL string
}}

func NewCrawler() *Crawler {{
    return &Crawler{{
        client: &http.Client{{
            Timeout: {config.timeout} * time.Second,
        }},
        baseURL: "{url.split('?')[0]}",
    }}
}}
'''
        
        if signature_logic:
            code += f'''
func (c *Crawler) generateSignature(params map[string]string) string {{
    // Sort keys and build message
    keys := make([]string, 0, len(params))
    for k := range params {{
        keys = append(keys, k)
    }}
    sort.Strings(keys)
    
    var message strings.Builder
    for i, k := range keys {{
        if i > 0 {{
            message.WriteString("&")
        }}
        message.WriteString(k)
        message.WriteString("=")
        message.WriteString(params[k])
    }}
'''
            
            algo = signature_logic.get("algorithm", "hmac-sha256")
            if "hmac" in algo.lower():
                code += f'''
    secret := "{signature_logic.get("key", "secret")}"
    h := hmac.New(sha256.New, []byte(secret))
    h.Write([]byte(message.String()))
    return hex.EncodeToString(h.Sum(nil))'''
            code += '''
    return ""
}
'''
        
        code += f'''
func (c *Crawler) makeRequest(path string, method string) (string, error) {{
    req, err := http.NewRequest(method, c.baseURL+path, nil)
    if err != nil {{
        return "", err
    }}
'''
        
        if headers:
            for k, v in headers.items():
                code += f'    req.Header.Set("{k}", "{v}")\n'
        
        code += '''
    resp, err := c.client.Do(req)
    if err != nil {
        return "", err
    }
    defer resp.Body.Close()
    
    body, err := ioutil.ReadAll(resp.Body)
    if err != nil {
        return "", err
    }
    return string(body), nil
}}

func main() {{
    c := NewCrawler()
    resp, err := c.makeRequest("", "GET")
    if err != nil {{
        fmt.Println("Error:", err)
        return
    }}
    fmt.Println("Response:", resp)
}}
'''
        
        return code
    
    def _generate_curl(
        self,
        url: str,
        method: str,
        headers: Optional[dict],
        params: Optional[dict],
        body: Optional[dict],
        signature_logic: Optional[dict],
        config: CodeGenConfig,
    ) -> str:
        """Generate curl command"""
        
        code = f'''#!/bin/bash
# Curl command - Generated by Axelo JSReverse
# Target: {url}

URL="{url}"
'''
        
        if headers:
            code += '\n# Headers\n'
            for k, v in headers.items():
                code += f'-H "{k}: {v}" \\\n'
        
        if params:
            code += '\n# Parameters\n'
            param_str = "&".join(f"{k}={v}" for k, v in params.items())
            code += f'-G --data-urlencode "{param_str}" \\\n'
        
        if body:
            code += '\n# Body\n'
            body_str = json.dumps(body) if isinstance(body, dict) else str(body)
            code += f'-d \'{body_str}\' \\\n'
        
        code += f'''
# Execute
curl -X {method} "$URL" \\
    -H "User-Agent: Mozilla/5.0" \\
    -H "Accept: application/json" \\
    --compressed
'''
        
        return code


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    "CodeGenConfig",
    "MultiLangCodeGenerator",
]
