TOPIC_FRONTIER_DISCOVERED = "axelo.frontier.discovered"
TOPIC_JOBS_REVERSE = "axelo.jobs.reverse"
TOPIC_JOBS_CRAWL = "axelo.jobs.crawl"
TOPIC_JOBS_BRIDGE = "axelo.jobs.bridge"
TOPIC_JOBS_SESSION_REFRESH = "axelo.jobs.session_refresh"
TOPIC_RESULTS_RAW = "axelo.results.raw"
TOPIC_RESULTS_NORMALIZED = "axelo.results.normalized"
TOPIC_RESOURCE_EVENTS = "axelo.resource.events"
TOPIC_PLATFORM_EVENTS = "axelo.platform.events"

PLATFORM_TOPICS = [
    TOPIC_FRONTIER_DISCOVERED,
    TOPIC_JOBS_REVERSE,
    TOPIC_JOBS_CRAWL,
    TOPIC_JOBS_BRIDGE,
    TOPIC_JOBS_SESSION_REFRESH,
    TOPIC_RESULTS_RAW,
    TOPIC_RESULTS_NORMALIZED,
    TOPIC_RESOURCE_EVENTS,
    TOPIC_PLATFORM_EVENTS,
]
