"""
VM replicator — builds an executable replica of a detected custom VM.

Three strategies are supported:

JS_BRIDGE (default)
    Extracts the dispatch function from the original JS and wraps it in a
    NodeRunner-compatible harness.  The result is a standalone .js file that
    can be executed via the existing NodeRunner infrastructure.

PYTHON_INTERPRETER
    Emits a Python class with one method per opcode handler derived from the
    handler_map.  This is an approximation; complex control-flow may need
    manual cleanup.

AI_DECOMPILE
    Sends the bytecode + handler map to Claude and asks it to produce
    readable pseudocode / Python.  Requires an AIClient instance to be
    passed in.
"""
from __future__ import annotations

import json
import textwrap
from enum import Enum

import structlog

from axelo.analysis.virtualization.extractor import BytecodeExtract

log = structlog.get_logger(__name__)


class VMReplicaStrategy(str, Enum):
    JS_BRIDGE          = "js_bridge"
    PYTHON_INTERPRETER = "python_interpreter"
    AI_DECOMPILE       = "ai_decompile"


# ---------------------------------------------------------------------------
# JS bridge template
# ---------------------------------------------------------------------------

_JS_BRIDGE_TEMPLATE = """\
/**
 * Axelo VM Replica — JS Bridge
 *
 * Auto-generated by axelo.analysis.virtualization.replicator
 *
 * This file wraps the extracted dispatch function so that the NodeRunner
 * can call vm_run(bytecode, constantPool, input) and receive structured
 * output.
 *
 * Usage (NodeRunner call):
 *   node vm_replica.js '<json>'
 *   e.g.  node vm_replica.js '{{"input": {{"key": "value"}}}}'
 *
 * Detected dispatcher : {vm_func}
 * Bytecode length     : {bytecode_len} instructions
 *
 * IMPORTANT: The dispatcher call below assumes a 3-argument signature
 *   ({vm_func}(bytecodeArr, constantPool, input)).
 * If the actual extracted function uses a different signature (e.g. only
 * takes a program counter or a stack object), adjust the call site manually.
 */
'use strict';

// ── Paste the extracted dispatch function(s) here ──────────────────────────
// AXELO_VM_FUNCTION_PLACEHOLDER
// ──────────────────────────────────────────────────────────────────────────

const BYTECODE      = {bytecode_json};
const CONSTANT_POOL = {pool_json};

function vm_run(bytecodeArr, constantPool, input) {{
    // Calls the dispatcher detected at runtime.
    // The dispatcher name ({vm_func}) must match the function pasted above.
    //
    // If calling with these 3 args is wrong, replace the line below with the
    // correct invocation for your specific VM (see header comment).
    if (typeof {vm_func} === 'function') {{
        return {vm_func}(bytecodeArr, constantPool, input);
    }}
    throw new Error('Dispatcher function "{vm_func}" not found — '
        + 'paste the extracted function above the placeholder comment.');
}}

// ── Entry point ────────────────────────────────────────────────────────────
const rawInput  = process.argv[2] ? JSON.parse(process.argv[2]) : {{}};
const result    = vm_run(BYTECODE, CONSTANT_POOL, rawInput.input || {{}});
process.stdout.write(JSON.stringify(result, null, 2));
"""

# ---------------------------------------------------------------------------
# Python interpreter template
# ---------------------------------------------------------------------------

_PYTHON_TEMPLATE_HEADER = """\
\"\"\"
Axelo VM Replica — Python Interpreter

Auto-generated by axelo.analysis.virtualization.replicator

This is an *approximate* Python reimplementation of the detected JS VM.
Handler logic was extracted from switch-case blocks via static analysis.
Complex control-flow may require manual review and adjustment.
\"\"\"
from __future__ import annotations

BYTECODE: list[int] = {bytecode_repr}
CONSTANT_POOL: list[str] = {pool_repr}


class VMInterpreter:
    \"\"\"Executes VM bytecode against the detected constant pool.\"\"\"

    def __init__(self, bytecode: list[int] = BYTECODE, pool: list[str] = CONSTANT_POOL) -> None:
        self.bytecode  = bytecode
        self.pool      = pool
        self.stack:  list = []
        self.locals: dict = {{}}
        self.pc      = 0
        self.result  = None

    def run(self, **kwargs) -> object:
        \"\"\"Execute the bytecode until halt or end of instructions.\"\"\"
        self.locals.update(kwargs)
        self.pc = 0
        while self.pc < len(self.bytecode):
            opcode = self.bytecode[self.pc]
            self.pc += 1
            handler = getattr(self, f'_op_{{opcode}}', self._op_unknown)
            handler(opcode)
        return self.result

    def _op_unknown(self, opcode: int) -> None:
        # Opcode not yet mapped — extend this class as needed
        pass

"""

_PYTHON_HANDLER_TEMPLATE = """\
    def _op_{opcode}(self, _opcode: int) -> None:
        # Extracted from: case {opcode}:
{body}
"""


# ---------------------------------------------------------------------------
# Replicator
# ---------------------------------------------------------------------------

class VMReplicator:
    """
    Build an executable replica of a detected custom VM.

    The returned string is the source code of the replica (JS or Python
    depending on *strategy*).
    """

    def build(
        self,
        extract: BytecodeExtract,
        strategy: VMReplicaStrategy = VMReplicaStrategy.JS_BRIDGE,
        ai_client=None,          # axelo.ai.client.AIClient | None
    ) -> str:
        if strategy == VMReplicaStrategy.JS_BRIDGE:
            return self._build_js_bridge(extract)
        if strategy == VMReplicaStrategy.PYTHON_INTERPRETER:
            return self._build_python_interpreter(extract)
        if strategy == VMReplicaStrategy.AI_DECOMPILE:
            return self._build_ai_decompile(extract, ai_client)
        raise ValueError(f"Unknown VMReplicaStrategy: {strategy!r}")

    # ------------------------------------------------------------------

    def _build_js_bridge(self, extract: BytecodeExtract) -> str:
        vm_func = extract.vm_function_name or "_vmDispatch"
        return _JS_BRIDGE_TEMPLATE.format(
            bytecode_json=json.dumps(extract.raw_bytecode),
            pool_json=json.dumps(extract.constant_pool),
            vm_func=vm_func,
            bytecode_len=len(extract.raw_bytecode),
        )

    # ------------------------------------------------------------------

    def _build_python_interpreter(self, extract: BytecodeExtract) -> str:
        handler_lines: list[str] = []
        for opcode_str, snippet in sorted(extract.handler_map.items(), key=lambda kv: int(kv[0])):
            # Convert JS snippet to a Python comment block (approximation)
            indented_body = textwrap.indent(
                "# JS source:\n" + textwrap.indent(snippet, "# "),
                "        ",
            )
            handler_lines.append(
                _PYTHON_HANDLER_TEMPLATE.format(opcode=opcode_str, body=indented_body)
            )

        header = _PYTHON_TEMPLATE_HEADER.format(
            bytecode_repr=repr(extract.raw_bytecode),
            pool_repr=repr(extract.constant_pool),
        )
        return header + "\n".join(handler_lines)

    # ------------------------------------------------------------------

    def _build_ai_decompile(self, extract: BytecodeExtract, ai_client) -> str:
        if ai_client is None:
            log.warning("vm_ai_decompile_no_client")
            return (
                "# AI decompilation requested but no AIClient was provided.\n"
                "# Re-run with ai_client=<AIClient instance> or choose a different strategy.\n"
            )

        handlers_text = "\n".join(
            f"case {k}:\n{v}" for k, v in list(extract.handler_map.items())[:30]
        )
        prompt = (
            "The following is a custom JavaScript VM dispatcher extracted from an obfuscated bundle.\n"
            f"Dispatcher function name: {extract.vm_function_name or 'unknown'}\n"
            f"Bytecode (first 64 opcodes): {extract.raw_bytecode[:64]}\n"
            f"Constant pool (first 20 entries): {extract.constant_pool[:20]}\n\n"
            "Handler map (opcode → handler source):\n"
            f"{handlers_text}\n\n"
            "Please produce:\n"
            "1. A plain-English description of what this VM computes\n"
            "2. A Python function `vm_run(bytecode, pool, **kwargs)` that "
            "   replicates the VM logic as faithfully as possible\n"
            "3. Notes on any opcodes you could not decompile\n"
        )

        try:
            response = ai_client.complete_sync(prompt)
            return f"# AI-decompiled VM replica\n# Prompt sent to {ai_client.model}\n\n{response}"
        except Exception as exc:
            log.warning("vm_ai_decompile_failed", error=str(exc))
            return f"# AI decompilation failed: {exc}\n"
